const TRANSITIONS = {
  NEW: ["MO_PENDING"],

  MO_PENDING: ["MO_BREAK_OPEN", "CONFIRMATION_PENDING"],

  MO_BREAK_OPEN: ["MO_PENDING", "PENDING_FO_RESPONSE"],

  CONFIRMATION_PENDING: [
  "SETTLEMENT_PENDING",
  "CONFIRMATION_BREAK",
  "LIASING_WITH_CPTY",
  "LIASING_WITH_FO"
],

CONFIRMATION_BREAK: [
  "LIASING_WITH_CPTY",
  "LIASING_WITH_FO",
  "CONFIRMATION_PENDING"
],

  SETTLEMENT_PENDING: ["READY_FOR_APPROVAL"],

  READY_FOR_APPROVAL: ["SETTLED", "SETTLEMENT_BREAK"],

  SETTLEMENT_BREAK: ["SETTLED"],

  SETTLED: ["RECON_PENDING"],

  RECON_PENDING: ["RECON_CLEARED", "UNMATCHED_BY_USER"],

  UNMATCHED_BY_USER: ["RECON_PENDING"],

  RECON_CLEARED: ["CLOSED"],

  CLOSED: [],

  PENDING_FO_RESPONSE: ["MO_BREAK_OPEN", "MO_PENDING"],

  LIASING_WITH_FO: ["CONFIRMATION_BREAK", "CONFIRMATION_PENDING", "LIASING_WITH_CPTY"],

  LIASING_WITH_CPTY: [
    "CONFIRMATION_PENDING",
    "CONFIRMATION_BREAK",
    "SETTLEMENT_PENDING",
    "SETTLEMENT_BREAK",
    "LIASING_WITH_FO"
  ]

};

module.exports = TRANSITIONS;