const TRANSITIONS = {
  NEW: ["MO_PENDING"],

  MO_PENDING: ["MO_BREAK_OPEN", "CONFIRMATION_PENDING"],

  MO_BREAK_OPEN: ["MO_PENDING", "PENDING_FO_RESPONSE"],

  CONFIRMATION_PENDING: [
  "SETTLEMENT_PENDING",
  "CONFIRMATION_BREAK",
  "LIASING_WITH_CPTY",
  "LIASING_WITH_FO"
],

CONFIRMATION_BREAK: [
  "LIASING_WITH_CPTY",
  "LIASING_WITH_FO",
  "CONFIRMATION_PENDING"
],

  SETTLEMENT_PENDING: ["SETTLEMENT_BREAK", "LIASING_WITH_CPTY"],

  SETTLEMENT_BREAK: ["LIASING_WITH_CPTY", "SETTLEMENT_PENDING", "PENDING_AMENDMENT"],

  // ======================================
  // SETTLEMENT WORKFLOW
  // Happy path:  SETTLEMENT_PENDING → LIASING_WITH_CPTY → PENDING_APPROVAL
  //              → Verification Bot → SETTLED | SETTLEMENT_PENDING (rejected)
  // Break path:  LIASING_WITH_CPTY → SETTLEMENT_BREAK → PENDING_AMENDMENT
  //              → AMENDED → PENDING_APPROVAL → SETTLED | SETTLEMENT_PENDING
  // ======================================
  PENDING_AMENDMENT: ["AMENDED"],

  AMENDED: ["PENDING_APPROVAL"],

  PENDING_APPROVAL: ["SETTLED", "SETTLEMENT_PENDING"],

  // APPROVED state kept for backward compat but no longer in primary flow
  APPROVED: ["SETTLED"],

  REJECTED_REVERIFY: ["PENDING_AMENDMENT", "SETTLEMENT_PENDING"],

  SETTLED: ["RECON_PENDING"],

  RECON_PENDING: ["RECON_CLEARED", "UNMATCHED_BY_USER"],

  UNMATCHED_BY_USER: ["RECON_PENDING"],

  RECON_CLEARED: ["CLOSED"],

  CLOSED: [],

  PENDING_FO_RESPONSE: ["MO_BREAK_OPEN", "MO_PENDING"],

  LIASING_WITH_FO: ["CONFIRMATION_BREAK", "CONFIRMATION_PENDING", "LIASING_WITH_CPTY"],

  LIASING_WITH_CPTY: [
    "CONFIRMATION_PENDING",
    "CONFIRMATION_BREAK",
    "SETTLEMENT_PENDING",
    "SETTLEMENT_BREAK",
    "LIASING_WITH_FO",
    "PENDING_APPROVAL"
  ]

};

module.exports = TRANSITIONS;