const TRANSITIONS = {
  NEW: ["MO_PENDING"],

  MO_PENDING: ["MO_BREAK_OPEN", "CONFIRMATION_PENDING"],

  MO_BREAK_OPEN: ["MO_PENDING", "PENDING_FO_RESPONSE"],

  CONFIRMATION_PENDING: [
  "SETTLEMENT_PENDING",
  "CONFIRMATION_BREAK",
  "LIASING_WITH_CPTY",
  "LIASING_WITH_FO"
],

CONFIRMATION_BREAK: [
  "LIASING_WITH_CPTY",
  "LIASING_WITH_FO",
  "CONFIRMATION_PENDING"
],

  SETTLEMENT_PENDING: ["READY_FOR_APPROVAL", "SETTLED", "SETTLEMENT_BREAK", "LIASING_WITH_CPTY"],

  READY_FOR_APPROVAL: ["SETTLED", "SETTLEMENT_BREAK"],

  SETTLEMENT_BREAK: ["SETTLED", "LIASING_WITH_CPTY", "SETTLEMENT_PENDING", "PENDING_AMENDMENT"],

  // ======================================
  // SYSTEM AMENDMENT + AUTOMATED APPROVAL WORKFLOW
  // Break Raised → Send to System for Amendment → PENDING_AMENDMENT
  //   → (system processes) AMENDED → Send for Approval → PENDING_APPROVAL
  //   → Verification Bot → APPROVED (→ SETTLED) | REJECTED_REVERIFY (re-amend / resubmit)
  // ======================================
  PENDING_AMENDMENT: ["AMENDED"],

  AMENDED: ["PENDING_APPROVAL"],

  PENDING_APPROVAL: ["APPROVED", "REJECTED_REVERIFY"],

  APPROVED: ["SETTLED"],

  REJECTED_REVERIFY: ["PENDING_AMENDMENT", "PENDING_APPROVAL"],

  SETTLED: ["RECON_PENDING"],

  RECON_PENDING: ["RECON_CLEARED", "UNMATCHED_BY_USER"],

  UNMATCHED_BY_USER: ["RECON_PENDING"],

  RECON_CLEARED: ["CLOSED"],

  CLOSED: [],

  PENDING_FO_RESPONSE: ["MO_BREAK_OPEN", "MO_PENDING"],

  LIASING_WITH_FO: ["CONFIRMATION_BREAK", "CONFIRMATION_PENDING", "LIASING_WITH_CPTY"],

  LIASING_WITH_CPTY: [
    "CONFIRMATION_PENDING",
    "CONFIRMATION_BREAK",
    "SETTLEMENT_PENDING",
    "SETTLEMENT_BREAK",
    "LIASING_WITH_FO",
    "SETTLED"
  ]

};

module.exports = TRANSITIONS;