const mongoose = require("mongoose");

const TradeSchema = new mongoose.Schema({

  tradeRef: { type: String, required: true, unique: true, index: true },
  originType: { type: String, default: "AUTO_GENERATED" },

  tradeDate: { type: Date },
  valueDate: { type: Date },

  currentStatus: { type: String, default: "MO_PENDING" },
  nextDesk: { type: String, index: true },

  amount: { type: Number },
  currency: { type: String },
  counterparty: { type: String },
  direction: { type: String },

  entity: { type: String },
  foRegion: { type: String },
  product: { type: String },
  tradeType: { type: String },
  settlementType: { type: String },

  age: { type: Number, default: 0 },

  // ======================================
  // DESK-SPECIFIC TRUTHS
  // Each desk has its own source of truth.
  // MO compares booking vs truths.mo
  // Confirmation compares trade economics vs truths.confirmation
  // ======================================
  truths: {
    universal: {
      amount: Number,
      valueDate: Date,
      currency: String,
      counterparty: String
    },
    mo: {
      amount: Number,
      valueDate: Date,
      currency: String,
      counterparty: String
    },
    confirmation: {
      amount: Number,
      valueDate: Date,
      currency: String
      // No counterparty mismatch at confirmation level
    },
    settlement: {
      amount: Number,
      valueDate: Date,
      currency: String,
      counterparty: String,
      beneficiaryName: String,
      beneficiaryBank: String,
      beneficiaryBIC: String,
      accountNumber: String,
      accountType: String,
      settlementMethod: String,
      correspondentBank: String,
      paymentReference: String,
      settlementDate: Date,
      settlementType: String
    }
  },

  booking: {
    amount: Number,
    valueDate: Date,
    currency: String,
    counterparty: String
  },

  settlementDetails: {
    beneficiaryName: String,
    beneficiaryBank: String,
    beneficiaryBIC: String,
    accountNumber: String,
    accountType: String,
    currency: String,
    settlementMethod: String,
    correspondentBank: String,
    paymentReference: String,
    settlementDate: Date,
    settlementType: String
  },

  // ======================================
  // AMENDMENTS
  // ======================================
  pendingAmendments: { type: Array, default: [] },

  // Full history of all amendments applied across the trade lifecycle
  amendmentHistory: [{
    amendmentNumber: Number,
    desk: String,
    field: String,
    oldValue: mongoose.Schema.Types.Mixed,
    newValue: mongoose.Schema.Types.Mixed,
    source: String,
    status: String,
    appliedAt: Date,
    appliedBy: String
  }],

  // ======================================
  // CONFIRMATION SCENARIO
  // Generated by tradeGenerator for trades that have
  // a confirmation-level discrepancy
  // ======================================
  confirmationScenario: {
    disputeType: { type: String, default: null },
    expectedEconomics: {
      amount: Number,
      valueDate: Date,
      currency: String
    },
    evidence: [{
      type: String,
      provided: { type: Boolean, default: false },
      requestedAt: Date,
      receivedAt: Date
    }]
  },

  // ======================================
  // SETTLEMENT SCENARIO
  // ======================================
  settlementOperationalStatus: { type: String, default: "READY" },
  
  settlementScenario: {
    scenarioId: String,
    scenarioType: String,
    settlementMethod: String,
    difficulty: String,
    hiddenIssue: String,
    expectedResolution: String,
    learningObjective: String,
    possibleOutcomes: [String],
    checkListModifiers: mongoose.Schema.Types.Mixed,
    metadata: mongoose.Schema.Types.Mixed
  },
  
  decisionLogs: [{
    timestamp: { type: Date, default: Date.now },
    action: String,
    decision: String,
    correctness: Boolean,
    operationalImpact: String,
    scenarioStage: String,
    aiFeedback: String,
    simulatedTimeConsumed: Number
  }],

  priority: { type: String, default: "Medium" },
  estimatedResolutionTime: Number,
  scenarioDifficulty: String,
  scenarioCompleted: { type: Boolean, default: false },

  // ======================================
  // FO ESCALATION (from Confirmation desk)
  // ======================================
  foEscalation: {
    status: { type: String, default: null },
    escalatedAt: Date,
    resolvedAt: Date,
    foResponse: String
  },

  foResponseReceived: { type: Boolean, default: false },
  cptyResponseReceived: { type: Boolean, default: false },

  // Escalation tracking for multi-round logic
  cptyContactCount: { type: Number, default: 0 },
  foContactCount: { type: Number, default: 0 },

  // Conversation status — persists resolve state across server restarts
  conversation: {
    status: { type: String, default: null },
    resolvedAt: { type: Date, default: null }
  },

  // If assigned to a user session, store the userId
  assignedTo: { type: String, default: null, index: true },

  // Whether this trade was auto-generated by the system
  isAutoGenerated: { type: Boolean, default: true },

  // XML audit trail for auto-generated trades (system history before user assignment)
  auditXml: { type: String, default: null }

}, { timestamps: true });

module.exports = mongoose.model("Trade", TradeSchema);
